"""
Critical Minerals Records Studio - web wrapper.

A Streamlit front-end over build_cache.py, merge_sources.py,
fetch_records_stage.py, and the axis_scorer config. Designed for adopters
who are comfortable with a browser UI but not with terminal commands.

Run:
    streamlit run app.py

The app assumes it's launched from the repo root (the directory containing
parser.py, scorer.py, build_cache.py, etc.).
"""

from __future__ import annotations

import importlib
import json
import logging
import re
import sys
import traceback
from contextlib import contextmanager
from pathlib import Path

import streamlit as st

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

import event_contract  # noqa: E402
import github_fetch  # noqa: E402
import html_embed  # noqa: E402
import setup_state  # noqa: E402


# --------------------------------------------------------------------------
# Module reload helpers (Streamlit reruns top-to-bottom on every interaction,
# but Python caches imports — so we reimport adopter modules on demand).
# --------------------------------------------------------------------------


def reimport(name: str):
    sys.modules.pop(name, None)
    return importlib.import_module(name)


def _read(name: str) -> str:
    return (ROOT / name).read_text(encoding="utf-8")


def parser_implemented() -> bool:
    # The shipped stub carries a unique sentinel; a generic/sample/custom
    # parser does not. This avoids false-flagging a real parser that happens
    # to contain the substring "raise NotImplementedError".
    return setup_state.PARSER_STUB_SENTINEL not in _read("parser.py")


def scorer_implemented() -> bool:
    # No scorer stub ships by default (scorer.py imports axis_scorer), so the
    # only way it's "unimplemented" is an adopter explicitly stubbing it.
    return "raise NotImplementedError" not in _read("scorer.py")


def taxonomy_opted_in() -> bool:
    src = _read("taxonomy.py")
    # Adopter has either set DEFAULT_TAXONOMY_REPO or rewritten load_taxonomy.
    if 'DEFAULT_TAXONOMY_REPO = ""' not in src:
        return True
    return "raise NotImplementedError" not in src


def _write_seam_file(path: Path, content: str) -> str | None:
    """Write a seam file (parser.py / scorer.py), backing up any existing
    *different* content to ``<name>.bak`` first. Returns the backup path (str)
    if one was made, else None. This is what makes the one-click setup buttons
    non-destructive — a hand-edited file is never silently overwritten."""
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return None
        backup = path.with_name(path.name + ".bak")
        backup.write_text(existing, encoding="utf-8")
        path.write_text(content, encoding="utf-8")
        return str(backup)
    path.write_text(content, encoding="utf-8")
    return None


class _ListLogHandler(logging.Handler):
    def __init__(self) -> None:
        super().__init__(level=logging.WARNING)
        self.messages: list[str] = []

    def emit(self, record: logging.LogRecord) -> None:
        self.messages.append(record.getMessage())


@contextmanager
def _capture_warnings():
    """Collect WARNING+ log records emitted by the toolkit modules during a
    parse/build, so they can be surfaced in the browser instead of vanishing
    into the terminal the non-technical user never sees."""
    handler = _ListLogHandler()
    root = logging.getLogger()
    prev_level = root.level
    root.addHandler(handler)
    if prev_level == logging.NOTSET or prev_level > logging.WARNING:
        root.setLevel(logging.WARNING)
    try:
        yield handler
    finally:
        root.removeHandler(handler)
        root.setLevel(prev_level)


# --------------------------------------------------------------------------
# Generic JSON adapter (no-code path for adopters with clean JSON exports)
# --------------------------------------------------------------------------

GENERIC_ADAPTER_SHIM = '''"""Adopter parser — generic JSON adapter (no custom code).

Generated by the Records Toolkit when you clicked "Use generic JSON
adapter" in the setup app. Reads parser_config.json and delegates to
generic_json_parser.py.

If your data outgrows this adapter (you need URL construction, date
inference from filenames, multi-source merging, etc.), replace this
file with a custom parse_corpus() implementation.
"""

import json
from pathlib import Path
from typing import Iterable

from generic_json_parser import parse_corpus_with_config

_CONFIG_PATH = Path(__file__).resolve().parent / "parser_config.json"


def parse_corpus(source_root) -> Iterable[dict]:
    config = json.loads(_CONFIG_PATH.read_text(encoding="utf-8"))
    return parse_corpus_with_config(source_root, config)
'''


def using_generic_adapter() -> bool:
    return setup_state.parser_mode(_read("parser.py")) == setup_state.GENERIC


def load_parser_config() -> dict:
    path = ROOT / "parser_config.json"
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {"source_label": "", "array_key": None, "field_map": {}}


def save_parser_config(config: dict) -> None:
    (ROOT / "parser_config.json").write_text(
        json.dumps(config, indent=2), encoding="utf-8"
    )


def sniff_sample_record(source_root_str: str, array_key: str | None = None) -> dict | None:
    """Peek at the first record in the user's archive so we can pre-fill
    the field-mapping dropdowns. Returns None on any error — the caller
    falls back to a less helpful manual-entry mode."""
    try:
        path = Path(source_root_str)
        files = [path] if path.is_file() else sorted(path.glob("*.json"))
        if not files:
            return None
        data = json.loads(files[0].read_text(encoding="utf-8"))
        if array_key and isinstance(data, dict):
            data = data.get(array_key, [])
        if isinstance(data, list) and data and isinstance(data[0], dict):
            return data[0]
    except Exception:
        return None
    return None


# --------------------------------------------------------------------------
# JS-literal escaping used by the publishing-tool sync (Tab 4 "Apply changes")
# --------------------------------------------------------------------------


def js_str(value: str) -> str:
    """Escape a Python str into a JS double-quoted string literal.

    Used by the publishing-tool sync to inject adopter-entered values into the
    DEFAULT_CLEARANCES / DEFAULT_DRAFTER regions of records-stage.html. Escapes
    the obvious special characters and ``</`` so a stray ``</script>`` in the
    value can't close the surrounding ``<script>`` tag.

    Module-level so the pytest suite can import and test it directly.
    """
    escaped = (
        value.replace("\\", "\\\\")
             .replace('"', '\\"')
             .replace("\n", "\\n")
             .replace("\r", "\\r")
             .replace("\t", "\\t")
             .replace("</", "<\\/")
    )
    return f'"{escaped}"'


# --------------------------------------------------------------------------
# Clearance-chain Word-doc parser (used by Tab 4)
# --------------------------------------------------------------------------

_CLEARANCE_STATUSES = ["Required Clearance", "Info", "Info*", "N/A"]


def _normalize_status(raw: str) -> str:
    """Map free-text status cells from an uploaded doc onto the four
    canonical values the data editor expects. Falls back to 'Required
    Clearance' if nothing matches — the adopter can correct in the editor."""
    s = (raw or "").strip().lower()
    if not s:
        return "Required Clearance"
    if s in ("info*", "info notice", "info-notice"):
        return "Info*"
    if s.startswith("info"):
        return "Info"
    if s.startswith("n/a") or s.startswith("na") or s.startswith("not"):
        return "N/A"
    if "req" in s or s in ("r", "clear", "clearance"):
        return "Required Clearance"
    return "Required Clearance"


def parse_clearance_chain_docx(raw_bytes: bytes) -> list[dict]:
    """Extract a clearance chain from the first table in a Word doc. Returns
    a list of {code, status} dicts ready for the data editor. Raises
    RuntimeError with a friendly message if the doc has no usable table."""
    try:
        import docx  # python-docx
    except ImportError as e:
        raise RuntimeError(
            "Word-doc parsing needs the python-docx package. "
            "Run `pip install -r requirements.txt` and restart this app."
        ) from e

    from io import BytesIO
    doc = docx.Document(BytesIO(raw_bytes))
    if not doc.tables:
        raise RuntimeError(
            "Couldn't find any tables in that Word document. The clearance "
            "chain needs to be a two-column table (office name / default status)."
        )
    table = doc.tables[0]
    rows = []
    for i, row in enumerate(table.rows):
        cells = [c.text.strip() for c in row.cells]
        if len(cells) < 2:
            continue
        code, status_raw = cells[0], cells[1]
        # Skip header rows heuristically: status column says 'status', or
        # the first cell looks like a column header.
        if i == 0 and (
            status_raw.lower() in ("status", "default status", "clearance status")
            or code.lower() in ("office", "office / code", "code", "bureau")
        ):
            continue
        if not code:
            continue
        rows.append({"code": code, "status": _normalize_status(status_raw)})
    if not rows:
        raise RuntimeError(
            "The first table in your document had no usable rows. The toolkit "
            "looks for a two-column layout: office name in column 1, default "
            "status in column 2."
        )
    return rows


# --------------------------------------------------------------------------
# Page setup
# --------------------------------------------------------------------------

st.set_page_config(
    page_title="Critical Minerals Records Studio",
    layout="wide",
    initial_sidebar_state="expanded",
)


# Custom styling — mirrors the FRUS records-stage.html palette AND its
# component treatment (gradient masthead, navy card-header bars, soft focus
# rings, uppercase field caps) so the two tools read as siblings. Typography
# is Public Sans (USWDS sans) throughout, matching the publishing tool. Hides
# the Streamlit deploy/menu chrome an adopter doesn't need to see.
st.markdown(
    """
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Public+Sans:wght@400;500;600;700&display=swap');

    :root {
      --navy:   #003366;
      --navy2:  #004080;
      --blue:   #2a6db5;
      --light:  #e8f0f8;
      --border: #b0c4de;
      --red:    #c00000;
      --green:  #1a7a3a;
      --warn:   #c87000;
      --white:  #ffffff;
      --bg:     #f4f7fb;
      --text:   #1a1a2e;
      --muted:  #6b7c93;
    }

    /* Hide Streamlit's deploy / hamburger / footer chrome */
    [data-testid="stToolbar"], [data-testid="stDecoration"] { display: none !important; }
    #MainMenu, footer { display: none !important; }
    header[data-testid="stHeader"] { background: var(--bg); }

    /* Page background + body text */
    .stApp { background: var(--bg); color: var(--text); }
    .stApp, .stMarkdown p, .stMarkdown li, .stCaption {
        font-family: 'Public Sans', 'Helvetica Neue', Arial, sans-serif;
    }
    .stCaption, [data-testid="stCaptionContainer"] { color: var(--muted); }

    /* Headings — federal sans, navy */
    h1, h2, h3, h4, h5, h6 {
        font-family: 'Public Sans', 'Helvetica Neue', sans-serif !important;
        color: var(--navy) !important;
        font-weight: 600;
        letter-spacing: -0.01em;
    }
    h1 { font-weight: 700; }

    /* Sidebar — white panel, federal sans for the checklist */
    section[data-testid="stSidebar"] {
        background: var(--white);
        border-right: 1px solid var(--border);
    }
    /* Apply Public Sans to text elements only — must NOT cover icon <span>s,
       which use the Material Symbols font for the expander arrows etc. */
    section[data-testid="stSidebar"] p,
    section[data-testid="stSidebar"] li,
    section[data-testid="stSidebar"] label,
    section[data-testid="stSidebar"] h1,
    section[data-testid="stSidebar"] h2,
    section[data-testid="stSidebar"] h3,
    section[data-testid="stSidebar"] h4,
    section[data-testid="stSidebar"] h5,
    section[data-testid="stSidebar"] h6,
    section[data-testid="stSidebar"] button,
    section[data-testid="stSidebar"] input,
    section[data-testid="stSidebar"] [data-testid="stMarkdownContainer"] {
        font-family: 'Public Sans', sans-serif !important;
    }
    section[data-testid="stSidebar"] h2 { color: var(--navy) !important; font-size: 1.1rem !important; }

    /* Tabs */
    .stTabs [data-baseweb="tab-list"] { gap: 6px; border-bottom: 1px solid var(--border); }
    .stTabs [data-baseweb="tab"] {
        font-family: 'Public Sans', sans-serif !important;
        font-weight: 600; color: var(--muted);
        padding: 10px 14px; background: transparent;
    }
    .stTabs [aria-selected="true"] { color: var(--navy) !important; }
    .stTabs [data-baseweb="tab-highlight"] { background: var(--blue) !important; height: 3px !important; }

    /* Buttons */
    .stButton button, .stDownloadButton button {
        font-family: 'Public Sans', sans-serif !important;
        font-weight: 600;
        border-radius: 6px;
        border: 1.5px solid var(--border);
        color: var(--navy);
        background: var(--white);
    }
    .stButton button:hover, .stDownloadButton button:hover {
        border-color: var(--blue); color: var(--blue); background: var(--light);
    }
    .stButton button[kind="primary"], .stDownloadButton button[kind="primary"] {
        background: var(--navy) !important; border-color: var(--navy) !important; color: var(--white) !important;
    }
    .stButton button[kind="primary"]:hover, .stDownloadButton button[kind="primary"]:hover {
        background: var(--blue) !important; border-color: var(--blue) !important; color: var(--white) !important;
    }

    /* Inputs */
    .stTextInput input, .stTextArea textarea, .stNumberInput input {
        font-family: 'Public Sans', sans-serif !important;
        border-color: var(--border) !important;
    }
    .stTextInput input:focus, .stTextArea textarea:focus, .stNumberInput input:focus {
        border-color: var(--blue) !important; box-shadow: 0 0 0 3px rgba(42,109,181,.15) !important;
    }

    /* Code (use it sparingly — only for genuine identifiers) */
    code, .stCode {
        font-family: 'SF Mono', Menlo, Consolas, monospace !important;
        background: var(--light); color: var(--navy);
        padding: 1px 6px; border-radius: 3px; font-size: 0.9em;
    }

    /* Sliders — match the FRUS blue */
    .stSlider [role="slider"] { background: var(--blue) !important; border-color: var(--blue) !important; }

    /* Info/warning/success boxes — less Streamlit-default, more federal */
    [data-testid="stAlert"] { border-radius: 6px; border-left-width: 4px; font-family: 'Public Sans', sans-serif; }

    /* Field labels — uppercase federal caps, like the publishing tool */
    [data-testid="stWidgetLabel"] p {
        text-transform: uppercase; letter-spacing: .5px;
        font-size: 12px !important; font-weight: 700 !important; color: var(--navy) !important;
    }

    /* Header banner — mirrors the publishing tool's gradient masthead */
    .atb-header {
        background: linear-gradient(135deg, var(--navy) 0%, var(--navy2) 100%);
        color: var(--white);
        padding: 20px 28px;
        border-radius: var(--radius);
        display: flex; align-items: center; gap: 16px;
        box-shadow: 0 2px 8px rgba(0,0,0,.18);
        margin-bottom: 22px;
    }
    .atb-header .seal {
        width: 52px; height: 52px; flex-shrink: 0;
        background: rgba(255,255,255,.15); border-radius: 50%;
        display: flex; align-items: center; justify-content: center; font-size: 26px;
    }
    .atb-header h1 {
        color: var(--white) !important; font-size: 24px !important;
        font-weight: 700 !important; letter-spacing: .3px; margin: 0 !important;
    }
    .atb-header p { color: rgba(255,255,255,.85); font-size: 13px; margin: 3px 0 0; }

    /* Section header bars — solid navy, like the tool's .card-header */
    .atb-card-header {
        background: var(--navy); color: var(--white) !important;
        padding: 11px 18px; border-radius: var(--radius);
        font-family: 'Public Sans', sans-serif; font-weight: 700;
        font-size: 16px; letter-spacing: .2px; margin: 6px 0 16px;
        box-shadow: 0 1px 4px rgba(0,0,0,.08);
    }
    /* Step sub-headers — lighter accent bar, like the tool's .tweet-card-header */
    .atb-sub-header {
        background: var(--light); color: var(--navy) !important;
        padding: 8px 14px; border-left: 4px solid var(--blue);
        border-radius: 0 5px 5px 0;
        font-family: 'Public Sans', sans-serif; font-weight: 700;
        font-size: 15px; letter-spacing: .2px; margin: 18px 0 14px;
    }

    /* Sidebar checklist — CSS status chips instead of emoji */
    .atb-check-row {
        display: flex; align-items: center; gap: 9px; margin: 7px 0;
        font-family: 'Public Sans', sans-serif; font-size: 14px;
    }
    .atb-check {
        width: 18px; height: 18px; border-radius: 50%; flex-shrink: 0;
        display: inline-flex; align-items: center; justify-content: center;
        font-size: 11px; font-weight: 700; line-height: 1;
    }
    .atb-check.done { background: var(--green); color: var(--white); }
    .atb-check.todo { background: transparent; border: 1.5px solid var(--border); }
    .atb-check-label { color: var(--text); }
    .atb-check.todo + .atb-check-label { color: var(--muted); }

    /* Tighter top padding so the banner doesn't float in space */
    .block-container { padding-top: 2rem; }
    </style>
    """,
    unsafe_allow_html=True,
)


def card_header(text: str):
    """Solid-navy section bar, mirroring the publishing tool's .card-header."""
    st.markdown(f'<div class="atb-card-header">{text}</div>', unsafe_allow_html=True)


def sub_header(text: str):
    """Lighter accent bar for sub-steps, like the tool's .tweet-card-header."""
    st.markdown(f'<div class="atb-sub-header">{text}</div>', unsafe_allow_html=True)


st.markdown(
    """
    <div class="atb-header">
      <div class="seal">🏛</div>
      <div>
        <h1>Critical Minerals Records Studio</h1>
        <p>Turn critical-minerals metadata into Critical Minerals Records Stage - set up records, scoring, taxonomy, branding, and export workflow in five steps below.</p>
      </div>
    </div>
    """,
    unsafe_allow_html=True,
)

# --- Sidebar status ------------------------------------------------------

with st.sidebar:
    st.header("Setup checklist")
    has_parser = parser_implemented()
    has_scorer = scorer_implemented()
    using_axis_scorer = (
        "from axis_scorer import score_event"
        in (ROOT / "scorer.py").read_text(encoding="utf-8")
    )
    has_taxonomy = taxonomy_opted_in()
    cache_exists = (ROOT / "events_cache.json").exists()
    html_path_sb = ROOT / "records-stage.html"
    html_exists = html_path_sb.exists() and html_path_sb.stat().st_size > 50_000

    def line(ok: bool, ok_text: str, bad_text: str):
        cls = "done" if ok else "todo"
        mark = "✓" if ok else ""
        txt = ok_text if ok else bad_text
        st.markdown(
            f'<div class="atb-check-row">'
            f'<span class="atb-check {cls}">{mark}</span>'
            f'<span class="atb-check-label">{txt}</span></div>',
            unsafe_allow_html=True,
        )

    line(has_parser, "Data parser ready", "Data parser needs a developer")
    line(has_scorer, "Scoring rules ready", "Scoring rules not set up")
    if using_axis_scorer:
        st.caption("&nbsp;&nbsp;&nbsp;&nbsp;(tuned with sliders in step 2)", unsafe_allow_html=True)
    line(has_taxonomy, "Subject categories in use", "Subject categories: skipped")
    line(cache_exists, "Catalog of events built", "Catalog of events: not built yet")
    line(html_exists, "Publishing tool ready", "Publishing tool missing")

    st.markdown("---")
    st.markdown("**📖 Documentation**")
    for label, fname in [
        ("Data shape", "data-contract.md"),
        ("Scoring guide", "scoring-guide.md"),
        ("Subject-scoped editions", "subject-scoped-editions.md"),
        ("What this can't do", "constraints.md"),
        ("Customization", "customization.md"),
    ]:
        with st.expander(label):
            doc_path = ROOT / "docs" / fname
            if doc_path.exists():
                st.markdown(doc_path.read_text(encoding="utf-8"))
            else:
                st.caption(f"docs/{fname} is missing.")

# --- Tabs -----------------------------------------------------------------

tab_connect, tab_score, tab_subjects, tab_customize, tab_build = st.tabs(
    [
        "1️⃣  Connect corpus",
        "2️⃣  Tune scoring",
        "3️⃣  Subjects (optional)",
        "4️⃣  Customize HTML",
        "5️⃣  Build & download",
    ]
)


# ==========================================================================
# Tab 1 — Connect corpus
# ==========================================================================

with tab_connect:
    card_header("Connect your archive")
    st.caption(
        "Three small steps to turn your documents into a catalog the publishing "
        "tool can browse, filter, draft from, and export for review."
    )

    using_generic = using_generic_adapter()

    # ---- Current state line -----------------------------------------------
    # "Where am I?" — show which approach is currently wired up, so the
    # user isn't guessing at the starting state. Driven by the recorded setup
    # state (setup_state), not by grepping parser.py for magic strings.
    _parser_src = (ROOT / "parser.py").read_text(encoding="utf-8")
    _mode = setup_state.parser_mode(_parser_src)
    if _mode == setup_state.GENERIC:
        _cfg = load_parser_config()
        _label = _cfg.get("source_label") or "My Archive"
        st.success(
            f"**Currently using:** the no-code adapter, set up for **{_label}**. "
            "Adjust the field mapping in step 3 if needed, or switch approaches below."
        )
    elif _mode == setup_state.SAMPLE:
        st.info("**Currently using:** the sample (5-event toy archive).")
    elif _mode == setup_state.STUB:
        st.warning(
            "**No parser set up yet.** Pick an option in step 1 below to get started."
        )
    else:
        st.info("**Currently using:** a custom parser in `parser.py`.")

    # ========================================================================
    # Step 1 — Pick how the toolkit reads your data
    # ========================================================================
    sub_header("Step 1 · How will the toolkit read your data?")
    st.caption("You can switch later — nothing here is permanent.")

    # Primary path: the no-code adapter, full-width with a "Recommended" hint.
    with st.container(border=True):
        cols = st.columns([3, 1], vertical_alignment="center")
        with cols[0]:
            st.markdown(
                "**✨ No-code · for most archives** &nbsp;&nbsp;"
                "<span style='color:#6b7c93;font-size:12px;'>Recommended</span>",
                unsafe_allow_html=True,
            )
            st.caption(
                "Best when your archive is already a JSON file (or a folder of "
                "JSON files). The toolkit reads the first record, and you confirm "
                "which field is the title, the date, the URL, etc. via dropdowns."
            )
        with cols[1]:
            _custom_now = _mode == setup_state.CUSTOM
            _ok_generic = True
            if _custom_now and not using_generic:
                _ok_generic = st.checkbox(
                    "Replace my custom parser.py",
                    key="confirm_generic_overwrite",
                    help="Your current parser.py will be backed up to parser.py.bak first.",
                )
            if st.button(
                "Use the no-code path",
                key="install_generic",
                type="primary" if not using_generic else "secondary",
                use_container_width=True,
                disabled=using_generic or not _ok_generic,
            ):
                backup = _write_seam_file(ROOT / "parser.py", GENERIC_ADAPTER_SHIM)
                if not (ROOT / "parser_config.json").exists():
                    save_parser_config({
                        "source_label": "My Archive",
                        "array_key": None,
                        "field_map": {},
                    })
                setup_state.save(parser_mode=setup_state.GENERIC)
                st.session_state["parser_chosen"] = True
                if backup:
                    st.info(f"Your previous parser.py was saved to `{backup}`.")
                st.success("Switched to the no-code adapter. Map your fields in step 3.")
                st.rerun()

    # Secondary paths — collapsed by default. Most adopters will take the
    # no-code path; devs and explorers can expand to see the alternatives.
    with st.expander("Other ways to read your data"):
        sec1, sec2 = st.columns(2)
        with sec1:
            st.markdown("**👀 Kick the tires with sample data**")
            st.caption(
                "Loads the 5-event toy archive shipped with the toolkit. "
                "Useful for seeing what the rest of the app feels like before "
                "you connect your real data."
            )
            _ok_sample = True
            if _mode == setup_state.CUSTOM:
                _ok_sample = st.checkbox(
                    "Replace my custom parser.py with the sample",
                    key="confirm_sample_overwrite",
                    help="Your current parser.py will be backed up to parser.py.bak first.",
                )
            if st.button(
                "Use the sample",
                key="copy_parser",
                use_container_width=True,
                disabled=not _ok_sample,
            ):
                backup = _write_seam_file(
                    ROOT / "parser.py",
                    (ROOT / "examples" / "example_parser.py").read_text(encoding="utf-8"),
                )
                setup_state.save(parser_mode=setup_state.SAMPLE)
                st.session_state["parser_chosen"] = True
                if backup:
                    st.info(f"Your previous parser.py was saved to `{backup}`.")
                st.success("Switched to the sample. Reload to continue.")
                st.rerun()
        with sec2:
            st.markdown("**🛠 Custom code (for developers)**")
            st.caption(
                "Your archive needs custom Python — XML walks, AI-assisted PDF "
                "extraction, URL construction. Edit `parser.py` directly. "
                "Adapters that need preprocessing (PDF → JSON, OCR, web scrapes) "
                "live alongside the parser; see `data/state-magazine/` for a "
                "worked example. The **Data shape** doc in the sidebar describes "
                "the record format `parse_corpus()` must produce."
            )

    st.markdown("")

    # ========================================================================
    # Step 2 — Point at your data
    # ========================================================================
    sub_header("Step 2 · Point at your data")

    # ---- Optional: fetch the corpus from a public GitHub repo --------------
    # Some archives are published as public repos (e.g. the Office of the
    # Historian's FRUS volumes at github.com/historyatstate/frus) rather than
    # living on your computer. Clone one here and Records Studio will point the
    # path field below at the local checkout. The corpus-specific reading logic
    # still lives in your parser; this only fetches the files.
    with st.expander("📥 Fetch from a public GitHub repo (optional)"):
        st.caption(
            "If your archive lives in a public GitHub repository instead of on "
            "this computer, point at it here. Example: `historyatstate/frus`. "
            "Two ways to read it:"
        )
        st.markdown(
            "- **Stream (no download)** — read the files over the network as the "
            "catalog builds; **nothing is stored on disk**. Best when the repo is "
            "large or your disk is tight. Slower, and re-reads each time you build.\n"
            "- **Clone locally** — download a shallow copy to a temp folder once, "
            "then read from disk. Faster rebuilds, but needs room for the repo."
        )
        gh_repo = st.text_input(
            "GitHub repository (owner/name or URL)",
            value=st.session_state.get("github_repo", ""),
            placeholder="historyatstate/frus",
            key="github_repo_input",
        )
        st.session_state["github_repo"] = gh_repo
        gh_cols = st.columns([2, 1, 1])
        do_stream = gh_cols[0].button(
            "Stream — no download", key="gh_stream", type="primary"
        )
        do_clone = gh_cols[1].button("Clone locally", key="gh_clone")
        do_refresh = gh_cols[2].button("Force re-clone", key="gh_refresh")

        if do_stream:
            try:
                owner, name = github_fetch.parse_repo(gh_repo)
                st.session_state["source_root"] = f"github:{owner}/{name}"
                st.success(
                    f"Set to **stream {owner}/{name}** with no local copy. "
                    "Continue to the final step to read it — volumes are fetched "
                    "on demand as the catalog builds."
                )
            except ValueError as e:
                st.error(str(e))
        elif do_clone or do_refresh:
            try:
                with st.spinner(
                    "Cloning from GitHub… (large repos like FRUS can take a "
                    "few minutes and need disk space)"
                ):
                    dest = github_fetch.clone_repo(gh_repo, force=do_refresh)
                st.session_state["source_root"] = str(dest)
                st.success(
                    f"Fetched **{gh_repo}** to `{dest}`. The path below now "
                    "points at it — continue to the final step to read it."
                )
            except ValueError as e:
                st.error(str(e))
            except Exception as e:
                st.error(f"Clone failed: {type(e).__name__}: {e}")
                with st.expander("Show the full error (for your developer)"):
                    st.code(traceback.format_exc())

    default_root = (
        str(ROOT / "examples")
        if (ROOT / "examples" / "sample_data.json").exists()
        else str(ROOT)
    )
    source_root = st.text_input(
        "Path to your data file or folder",
        value=st.session_state.get("source_root", default_root),
        help="A file or folder. The currently-active option determines what "
             "shape it expects. If your archive starts as PDFs and you're using "
             "an adapter with a preprocessing step (PDF → JSON), point at the "
             "directory of preprocessed outputs — not the raw PDFs.",
    )
    st.session_state["source_root"] = source_root

    # Catch the common "I pointed at the wrong thing" cases up front,
    # before the user clicks Read and gets a cryptic FileNotFoundError.
    _path = Path(source_root) if source_root else None
    if _path and _path.exists() and _path.is_dir():
        _has_djvu = any(_path.glob("*_djvu.txt"))
        _has_meta = any(_path.glob("*_meta.xml"))
        if _has_djvu and _has_meta:
            st.warning(
                "**Heads up:** that looks like a raw Internet Archive bundle "
                f"(`{_path.name}`). Most adapters can't read IA bundles directly — "
                "they need a preprocessing step first (e.g., the State Magazine "
                "adapter's `extract_articles.py`) that turns the bundle into "
                "structured JSON. Then point this field at the directory of "
                "preprocessed JSON files."
            )
        elif using_generic:
            _has_json = any(_path.glob("*.json"))
            if not _has_json:
                st.info(
                    "We don't see any `.json` files at that path. The no-code "
                    "adapter expects a JSON file or a folder containing one."
                )

    if using_generic:
        st.markdown("")
        sub_header("Step 3 · Match your fields")
        st.caption(
            "Your data probably uses different field names than the toolkit. "
            "We'll show you what we found in the first record — confirm the "
            "matches below."
        )

        config = load_parser_config()
        sample = sniff_sample_record(source_root, config.get("array_key"))

        if sample is None:
            st.info(
                "Point **step 2** at a JSON file (or a folder of JSON files), "
                "then refresh this page to map your fields."
            )
        else:
            from generic_json_parser import autodetect_field_map

            current_map = config.get("field_map") or autodetect_field_map(sample)
            sample_keys = list(sample.keys())
            NONE_OPT = "— none —"

            with st.form("field_mapping_form"):
                source_label = st.text_input(
                    "Name for this archive (shown on every event)",
                    value=config.get("source_label", "") or "My Archive",
                    help="e.g. 'Treasury Press Releases'",
                )

                def _selectbox(label, target, required: bool, help: str = ""):
                    opts = ([NONE_OPT] if not required else []) + sample_keys
                    current = current_map.get(target)
                    if current in sample_keys:
                        idx = opts.index(current)
                    else:
                        idx = 0
                    choice = st.selectbox(label, opts, index=idx, key=f"fm_{target}", help=help)
                    return None if choice == NONE_OPT else choice

                title_f = _selectbox(
                    "Field with the document title", "title", required=True,
                    help="The headline or document name. Required.",
                )
                url_f = _selectbox(
                    "Field with the document URL", "url", required=False,
                    help="Where this document lives on the web. Optional but recommended.",
                )

                date_mode = st.radio(
                    "How is the date stored?",
                    (
                        "In one field (e.g. '2024-03-15' or 'March 15, 2024')",
                        "In separate year / month / day fields",
                    ),
                    index=1 if current_map.get("year") else 0,
                )

                day_first = bool(config.get("date_day_first", False))
                if date_mode.startswith("In one"):
                    date_f = _selectbox("Field with the date", "date", required=True)
                    day_first = st.checkbox(
                        "Day comes before month in numeric dates "
                        "(e.g. 03/04/2020 means 4 March, not 3 April)",
                        value=day_first,
                        help="Only affects ambiguous DD/MM vs MM/DD numeric dates. "
                             "ISO dates (2020-03-04) and month-name dates are read "
                             "correctly either way.",
                    )
                    year_f = month_f = day_f = None
                else:
                    date_f = None
                    year_f = _selectbox("Field with the year", "year", required=True)
                    month_f = _selectbox("Field with the month (optional — defaults to January)", "month", required=False)
                    day_f = _selectbox("Field with the day (optional — defaults to the 1st)", "day", required=False)

                subjects_f = _selectbox(
                    "Field with subjects / tags / topics (optional)", "subjects", required=False,
                    help="A list of strings, or a comma-separated string. Powers the topic filter.",
                )
                desc_f = _selectbox(
                    "Field with description / summary (optional)", "description", required=False,
                )

                saved = st.form_submit_button("Save field mapping", type="primary")
                if saved:
                    save_parser_config({
                        "source_label": source_label,
                        "array_key": config.get("array_key"),
                        "date_day_first": day_first,
                        "field_map": {
                            "title": title_f, "url": url_f, "date": date_f,
                            "year": year_f, "month": month_f, "day": day_f,
                            "subjects": subjects_f, "description": desc_f,
                        },
                    })
                    st.success("Mapping saved. Read your archive below to test it.")

            with st.expander("Preview of the first record we found"):
                st.json(sample)

    st.markdown("")
    sub_header("Final step · Read your archive")
    st.caption(
        "Pulls every record from your data, scores each one, and shows the "
        "first five so you can confirm it looks right."
    )
    col_a, col_b = st.columns([1, 3])
    with col_a:
        run_parser = st.button("Read my archive", type="primary", disabled=not has_parser)

    if run_parser:
        try:
            adopter_parser = reimport("parser")
            with st.spinner("Reading your archive…"), _capture_warnings() as logs:
                events = list(adopter_parser.parse_corpus(Path(source_root)))
            st.session_state["parsed_events"] = events
            if not events:
                st.warning(
                    "The parser ran but didn't find any documents. "
                    "Double-check the path in step 2."
                )
            else:
                st.success(f"Found **{len(events):,}** documents.")
            for msg in logs.messages:
                st.warning(msg)
        except Exception as e:
            st.error(f"Something went wrong: {type(e).__name__}: {e}")
            with st.expander("Show the full error (for your developer)"):
                st.code(traceback.format_exc())

    events = st.session_state.get("parsed_events")
    if events:
        st.markdown("#### A peek at the first five")
        preview = []
        for ev in events[:5]:
            preview.append(
                {
                    "year": ev.get("year"),
                    "month": ev.get("month"),
                    "day": ev.get("day"),
                    "title": (ev.get("title") or "")[:80],
                    "source": ev.get("source"),
                    "subjects": ", ".join((ev.get("subjects") or [])[:3]),
                }
            )
        st.dataframe(preview, use_container_width=True, hide_index=True)

        # Schema sanity check against the shared event contract.
        report = event_contract.validate_events(events)
        if not report["ok"]:
            st.warning(
                f"{report['invalid']} document(s) don't match the data contract. "
                "Your developer needs to fix these in the parser:"
            )
            st.dataframe(
                [
                    {"document": p["event"], "problems": "; ".join(p["problems"])}
                    for p in report["problems"]
                ],
                use_container_width=True,
                hide_index=True,
            )
        else:
            st.info("Looks good — every document has the fields the toolkit needs. Move on to **Tune scoring**.")


# ==========================================================================
# Tab 2 — Tune scoring
# ==========================================================================

with tab_score:
    card_header("Decide what's worth surfacing")
    st.caption(
        "Your archive probably has thousands of documents or data rows. Most are not briefing-worthy. "
        "These sliders tell the toolkit what to prioritize."
    )

    using_axis = (
        "from axis_scorer import score_event"
        in (ROOT / "scorer.py").read_text(encoding="utf-8")
    )

    if not using_axis:
        st.info(
            "Your scoring rules are written in code (`scorer.py`). To adjust them "
            "with sliders here instead of editing code, switch to the slider-based scorer:"
        )
        _scorer_custom = scorer_implemented()  # not axis (checked above), not stub
        _ok_scorer = True
        if _scorer_custom:
            _ok_scorer = st.checkbox(
                "Replace my custom scorer.py with the slider-based scorer",
                key="confirm_scorer_overwrite",
                help="Your current scorer.py will be backed up to scorer.py.bak first.",
            )
        if st.button("Switch to slider-based scoring", disabled=not _ok_scorer):
            backup = _write_seam_file(
                ROOT / "scorer.py",
                "from axis_scorer import score_event  # noqa: F401\n",
            )
            if backup:
                st.info(f"Your previous scorer.py was saved to `{backup}`.")
            st.success("Switched. Reload the app to see the sliders.")
            st.rerun()
    else:
        cfg_path = ROOT / "scoring_config.json"

        # --- Start from a template -----------------------------------------
        # Scoring is an editorial choice. Templates give a deliberate starting
        # point: "FRUS standard" carries FRUS's original document-type,
        # prestige, and classification weights; "General starter" is a generic
        # scaffold to edit. Loading one replaces the current rules; the sliders
        # below then tune whatever was loaded.
        presets_dir = ROOT / "scoring_presets"
        preset_files = sorted(presets_dir.glob("*.json")) if presets_dir.exists() else []
        if preset_files:
            def _preset_label(p: Path) -> str:
                try:
                    return json.loads(p.read_text(encoding="utf-8")).get("_template_name") or p.stem
                except Exception:
                    return p.stem

            st.markdown("#### Start from a template")
            st.caption(
                "Load a ready-made scoring template, then tune the sliders below. "
                "Loading replaces your current rules."
            )
            tcols = st.columns([3, 1], vertical_alignment="bottom")
            chosen = tcols[0].selectbox(
                "Template",
                preset_files,
                format_func=_preset_label,
                key="scoring_preset_choice",
            )
            if tcols[1].button("Load template", key="load_scoring_preset", use_container_width=True):
                cfg_path.write_text(chosen.read_text(encoding="utf-8"), encoding="utf-8")
                st.success(f"Loaded **{_preset_label(chosen)}**. Tune below, then Save.")
                st.rerun()

        cfg = (
            json.loads(cfg_path.read_text(encoding="utf-8"))
            if cfg_path.exists()
            else {"threshold": 0, "axes": []}
        )

        cfg["threshold"] = st.slider(
            "Minimum score - records below this score won't appear in Critical Minerals Records Stage",
            min_value=0,
            max_value=100,
            value=int(cfg.get("threshold", 0)),
            step=1,
            help="Start with 0 to see everything. Raise it once you know your scoring "
                 "rules are giving important documents higher scores than routine ones.",
        )

        st.markdown("#### Scoring rules")
        st.caption(
            "Each rule asks one question about a document and adds points if the answer is yes. "
            "Higher total score = more important. Aim for the top score around 100 (the slider above "
            "uses the same scale). See **Scoring guide** in the sidebar for tips."
        )

        for axis_idx, axis in enumerate(cfg.get("axes", [])):
            with st.expander(f"**{axis.get('name', 'Rule')}**", expanded=False):
                st.caption(f"Reads from document field: `{axis.get('field', '')}`")
                if "weights" in axis:
                    new_weights = {}
                    for key, val in axis["weights"].items():
                        new_weights[key] = st.slider(
                            key, 0, 50, int(val), key=f"ax{axis_idx}_{key}",
                        )
                    axis["weights"] = new_weights
                if "any_of" in axis:
                    new_any = {}
                    for key, val in axis["any_of"].items():
                        new_any[key] = st.slider(
                            key, 0, 50, int(val), key=f"ax{axis_idx}_anyof_{key}",
                        )
                    axis["any_of"] = new_any
                if "if_truthy" in axis:
                    axis["if_truthy"] = st.slider(
                        "Points if this field is filled in", 0, 50, int(axis["if_truthy"]),
                        key=f"ax{axis_idx}_truthy",
                    )
                if "at_least" in axis:
                    new_ladder = []
                    for tier_idx, (cutoff, pts) in enumerate(axis["at_least"]):
                        c1, c2 = st.columns(2)
                        new_cutoff = c1.number_input(
                            f"Tier {tier_idx + 1} cutoff", value=int(cutoff),
                            key=f"ax{axis_idx}_cut_{tier_idx}",
                        )
                        new_pts = c2.slider(
                            f"Tier {tier_idx + 1} points", 0, 50, int(pts),
                            key=f"ax{axis_idx}_pts_{tier_idx}",
                        )
                        new_ladder.append([int(new_cutoff), int(new_pts)])
                    axis["at_least"] = new_ladder

        if st.button("Save these rules", type="primary"):
            cfg_path.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
            st.success("Saved. Rebuild the catalog (step 5) to apply.")

        # Live preview against the parsed events.
        parsed = st.session_state.get("parsed_events")
        if parsed:
            st.markdown("#### Your top 10 documents under these rules")
            st.caption(
                "Live preview using what you read in step 1. Tweak the sliders above "
                "and watch the order change."
            )
            reimport("axis_scorer")
            from axis_scorer import score_event as preview_score  # noqa: WPS433

            sample = [
                {
                    "score": preview_score(ev),
                    "title": (ev.get("title") or "")[:80],
                    "date": f"{ev.get('year', '')}-{ev.get('month', '')}-{ev.get('day', '')}",
                    "source": ev.get("source", ""),
                }
                for ev in parsed
            ]
            sample.sort(key=lambda r: -r["score"])
            st.dataframe(sample[:10], use_container_width=True, hide_index=True)
        else:
            st.info("Go back to step 1 and click **Read my archive** to see a live preview here.")


# ==========================================================================
# Tab 3 — Subjects (optional)
# ==========================================================================

with tab_subjects:
    card_header("Add subject categories (optional)")
    st.caption(
        "If your archive has subjects or topics (e.g. \"Fiscal Policy\", \"Tariffs\"), "
        "load them here so Records Stage can filter documents by topic. "
        "Skip this step if your archive doesn't have a subject vocabulary — the "
        "topic filter will hide itself."
    )

    mode = st.selectbox(
        "Where are your subject categories defined?",
        [
            "Skip — no subject categories",
            "Local file on this computer",
            "GitHub repository",
        ],
    )

    if mode == "Local file on this computer":
        uploaded = st.file_uploader(
            "Pick your subject categories file",
            type=["json"],
            help="A JSON file (usually called `taxonomy.json`) matching the format "
                 "described in the **Data shape** doc in the sidebar.",
            key="taxonomy_file_uploader",
        )
        if uploaded is not None:
            try:
                tax_mod = reimport("taxonomy")
                taxonomy_list = tax_mod.load_taxonomy_from_bytes(uploaded.getvalue())
                st.success(
                    f"Loaded {len(taxonomy_list)} subject categories from "
                    f"`{uploaded.name}`."
                )
                st.session_state["taxonomy_list"] = taxonomy_list
            except Exception as e:
                st.error(f"Couldn't load that file: {type(e).__name__}: {e}")

    elif mode == "GitHub repository":
        repo = st.text_input(
            "Repository (owner/name)",
            value=st.session_state.get("taxonomy_repo", ""),
            placeholder="e.g. youraccount/your-subject-taxonomy",
            help="Any GitHub repo that publishes an `exports/taxonomy.json` "
                 "in the format described in the **Data shape** doc in the sidebar.",
        )
        st.session_state["taxonomy_repo"] = repo
        if st.button("Load categories from GitHub"):
            try:
                tax_mod = reimport("taxonomy")
                taxonomy_list = tax_mod.load_taxonomy(repo=repo)
                st.success(f"Loaded {len(taxonomy_list)} subjects from GitHub.")
                st.session_state["taxonomy_list"] = taxonomy_list
            except Exception as e:
                st.error(f"Couldn't load: {type(e).__name__}: {e}")

    taxonomy_list = st.session_state.get("taxonomy_list")
    if taxonomy_list:
        with st.expander(f"Preview ({len(taxonomy_list)} subjects loaded)"):
            st.dataframe(
                [
                    {
                        "name": t.get("name", ""),
                        "category": t.get("category", ""),
                        "subcategory": t.get("subcategory", ""),
                    }
                    for t in taxonomy_list[:50]
                ],
                use_container_width=True,
                hide_index=True,
            )


# ==========================================================================
# Tab 4 — Customize HTML
# ==========================================================================

with tab_customize:
    card_header("Add your organization's branding")
    st.caption(
        "Customize Records Stage for your office — who's drafting, who "
        "needs to clear. These edits affect the publishing tool's clearance block."
    )

    html_path = ROOT / "records-stage.html"
    needs_fetch = (not html_path.exists()) or html_path.stat().st_size < 50_000

    if needs_fetch:
        st.warning(
            "The publishing tool file is missing. The toolkit ships a copy "
            "with the repo — restore it from your git history. (If you need "
            "to download a newer version, ask your developer to run "
            "`python fetch_records_stage.py` from the command line.)"
        )
    else:
        st.success(f"Publishing tool ready ({html_path.stat().st_size / 1024:.0f} KB).")

    if not needs_fetch:
        st.markdown("---")
        st.markdown("#### Drafter contact")
        drafted_by = st.text_input(
            "Who's drafting this campaign? (Shown in the clearance block.)",
            value=st.session_state.get("drafted_by", "Your Office — [Name], [Phone]"),
        )
        st.session_state["drafted_by"] = drafted_by

        st.markdown("#### Clearance chain")
        st.caption(
            "Each row appears as one clearance line in the publishing tool. "
            "For each office, pick a default status: Required Clearance, Info, "
            "Info*, or N/A."
        )

        # Optional: lift an existing chain from a Word doc the office already has.
        with st.expander("Already have a clearance chain document? Upload it"):
            st.caption(
                "If your office has an existing clearance template as a Word "
                "doc with a two-column table (office name / default status), "
                "upload it here and the rows will populate the editor below. "
                "You can still edit them after."
            )
            uploaded_chain = st.file_uploader(
                "Pick your clearance chain Word doc",
                type=["docx"],
                key="clearance_chain_uploader",
            )
            if uploaded_chain is not None:
                try:
                    parsed_rows = parse_clearance_chain_docx(uploaded_chain.getvalue())
                    st.session_state["clearance_rows"] = parsed_rows
                    st.success(
                        f"Loaded {len(parsed_rows)} row(s) from "
                        f"`{uploaded_chain.name}`. Review them below."
                    )
                except RuntimeError as e:
                    st.error(str(e))
                except Exception as e:
                    st.error(f"Couldn't read that file: {type(e).__name__}: {e}")

        default_chain = st.session_state.get(
            "clearance_rows",
            [
                {"code": "Office Director", "status": "Required Clearance"},
                {"code": "Bureau Front Office", "status": "Required Clearance"},
                {"code": "Public Affairs", "status": "Info"},
                {"code": "Legal", "status": "Info*"},
            ],
        )
        edited = st.data_editor(
            default_chain,
            use_container_width=True,
            num_rows="dynamic",
            column_config={
                "code": st.column_config.TextColumn("Office / Code"),
                "status": st.column_config.SelectboxColumn(
                    "Default status",
                    options=["Required Clearance", "Info", "Info*", "N/A"],
                ),
            },
            key="clearance_editor",
        )
        st.session_state["clearance_rows"] = edited

        if st.button("Apply changes to the publishing tool", type="primary"):
            page = html_path.read_text(encoding="utf-8")
            n_changes = 0

            # The setup tool rewrites two JS regions in records-stage.html:
            #   /* CLEARANCE_DEFAULTS */ ... /* /CLEARANCE_DEFAULTS */
            #   /* DRAFTED_BY */         ... /* /DRAFTED_BY */
            # Both regions hold JS literals that the publishing tool reads on
            # init. We emit valid JS source via js_str() (module-level helper
            # for testability) so values containing quotes, backslashes, or
            # angle brackets can't break the file or inject code.

            # ── DRAFTED_BY ────────────────────────────────────────────────
            drafter_js = f"\nconst DEFAULT_DRAFTER = {js_str(drafted_by)};\n"
            page, n = re.subn(
                r"(/\* DRAFTED_BY \*/)(.*?)(/\* /DRAFTED_BY \*/)",
                lambda m: f"{m.group(1)}{drafter_js}{m.group(3)}",
                page,
                count=1,
                flags=re.DOTALL,
            )
            n_changes += n

            # ── CLEARANCE_DEFAULTS ────────────────────────────────────────
            # Map setup-tool rows ({"code", "status"}) to the publishing
            # tool's 3-tuple shape [bureau, name, status]. We leave `name`
            # blank — adopters fill in clearer names per campaign.
            row_lines = []
            for row in edited:
                code = (row.get("code") or "").strip()
                status = (row.get("status") or "Required Clearance").strip()
                if not code:
                    continue
                row_lines.append(f"  [{js_str(code)}, \"\", {js_str(status)}],")
            array_body = "\n".join(row_lines)
            clearance_js = (
                "\nconst DEFAULT_CLEARANCES = [\n"
                f"{array_body}\n"
                "];\n"
            )
            page, n = re.subn(
                r"(/\* CLEARANCE_DEFAULTS \*/)(.*?)(/\* /CLEARANCE_DEFAULTS \*/)",
                lambda m: f"{m.group(1)}{clearance_js}{m.group(3)}",
                page,
                count=1,
                flags=re.DOTALL,
            )
            n_changes += n

            html_path.write_text(page, encoding="utf-8")
            if n_changes == 0:
                st.warning(
                    "Couldn't find the spots in the publishing tool's file to update. "
                    "The upstream HTML may have changed — you can also edit "
                    "`records-stage.html` directly."
                )
            else:
                st.success(f"Applied {n_changes} change(s) to the publishing tool.")


# ==========================================================================
# Tab 5 — Build & download
# ==========================================================================

with tab_build:
    card_header("Build your campaign tool")
    st.caption(
        "Two steps: build the catalog of events from your archive, then add the "
        "catalog into the publishing tool's HTML file. Download the result and "
        "you're ready to publish."
    )

    if not has_parser or not has_scorer:
        st.warning(
            "Finish steps 1 and 2 first — the toolkit needs a working data parser "
            "and a scoring rule before it can build the catalog."
        )

    col_a, col_b = st.columns([1, 1])
    build_clicked = col_a.button(
        "Build the catalog of events",
        type="primary",
        disabled=not (has_parser and has_scorer),
    )
    splice_clicked = col_b.button(
        "Add the catalog to the publishing tool",
        disabled=not (
            (ROOT / "events_cache.js").exists()
            and (ROOT / "records-stage.html").exists()
        ),
    )

    if build_clicked:
        try:
            reimport("axis_scorer")
            reimport("scorer")
            reimport("parser")
            reimport("taxonomy")
            build_cache = reimport("build_cache")
            with st.spinner("Reading your archive, scoring documents, building the catalog…"), \
                    _capture_warnings() as logs:
                summary = build_cache.build(
                    Path(st.session_state.get("source_root", ".")),
                    ROOT / "events_cache.json",
                    ROOT / "events_cache.js",
                )
            st.success("Catalog built.")
            if summary.get("invalid_dropped"):
                st.warning(
                    f"{summary['invalid_dropped']} document(s) were dropped for not "
                    "matching the data contract (see build details)."
                )
            for msg in logs.messages:
                st.warning(msg)
            with st.expander("Build details"):
                st.json(summary)
        except Exception as e:
            st.error(f"Something went wrong: {type(e).__name__}: {e}")
            with st.expander("Show the full error (for your developer)"):
                st.code(traceback.format_exc())

    if splice_clicked:
        try:
            ok = html_embed.sync_html_embed(
                ROOT / "events_cache.js", ROOT / "records-stage.html"
            )
            if ok:
                st.success("Added the catalog to the publishing tool. Download below.")
            else:
                st.warning(
                    "Couldn't find the spot in the publishing tool to add the catalog. "
                    "Did you set it up in step 4?"
                )
        except Exception as e:
            st.error(f"Something went wrong: {type(e).__name__}: {e}")

    st.markdown("---")
    st.markdown("#### Download")
    st.caption(
        "The publishing tool (`records-stage.html`) is the file you actually use "
        "day-to-day — open it in a browser. The other two files are the raw "
        "catalog data; keep them as backups."
    )

    for label, name, mime in [
        ("Publishing tool (HTML)", "records-stage.html", "text/html"),
        ("Catalog of events (compact, JS)", "events_cache.js", "application/javascript"),
        ("Catalog of events (full, JSON)", "events_cache.json", "application/json"),
    ]:
        path = ROOT / name
        if path.exists():
            st.download_button(
                f"{label} — `{name}`",
                data=path.read_bytes(),
                file_name=name,
                mime=mime,
                use_container_width=True,
            )
        else:
            st.caption(f"{label} (`{name}`) — not built yet")
