"""
Combined cache builder for the Federal Register edition.

Runs BOTH Federal Register adapters into one cache:
  * ``data/federal-register/`` — presidential documents (source "Presidential
    Documents")
  * ``data/state-department/``  — State Department documents (source "State
    Department")

so a single tool (``federal-register-stage.html``) carries both, with the
publishing tool's source-filter chips letting the user toggle between them.

It writes ``fr_events_cache.json`` / ``fr_events_cache.js`` and splices into
``federal-register-stage.html``. Like the other edition builders it imports only
the leaf modules (``cache_format``, ``event_contract``, ``html_embed``) and does
NOT import ``build_cache`` (whose module-level ``import parser`` ties it to the
repo's default wiring).

Subjects: only State documents carry subjects (from the FR's topics /
toc_subject), so the synthesized taxonomy — and thus the topic filter — reflects
the State side; presidential events simply have no subject indices.

Usage:
    python build_fr_cache.py
    python build_fr_cache.py --no-html-sync

Run each adapter's fetch script first for the full corpus; without them the
builder falls back to the checked-in seed samples:
    python data/federal-register/fetch_fr.py
    python data/state-department/fetch_state.py
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import logging
from collections import defaultdict
from pathlib import Path

import cache_format
import event_contract
import html_embed
from fr_themes import theme_for

log = logging.getLogger(__name__)

HERE = Path(__file__).resolve().parent
FR_DIR = HERE / "data" / "federal-register"
STATE_DIR = HERE / "data" / "state-department"
DEFAULT_JSON_OUT = HERE / "fr_events_cache.json"
DEFAULT_JS_OUT = HERE / "fr_events_cache.js"
DEFAULT_HTML = HERE / "federal-register-stage.html"

# (adapter dir, parser filename) for each source folded into the combined cache.
SOURCES = [
    (FR_DIR, "fr_parser"),
    (STATE_DIR, "state_parser"),
]


def _load_module(directory: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, directory / "parser.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _synthesize_taxonomy(events: list[dict]) -> list[dict]:
    # Group subjects under a broad theme (the filter's top tier). Themes come
    # from fr_themes.theme_for(); the subcategory level stays trivial ("All"),
    # which the publishing tool auto-collapses into an "All of <theme>" shortcut.
    cat_for: dict[str, str] = {}
    for e in events:
        for name in e.get("subjects", []) or []:
            if name not in cat_for:
                cat_for[name] = theme_for(name)
    names = sorted(cat_for, key=lambda n: (cat_for[n], n.lower()))
    return [{"name": n, "category": cat_for[n], "subcategory": "All"} for n in names]


def _enrich(events: list[dict], taxonomy: list[dict]) -> None:
    idx_of = {t["name"]: i for i, t in enumerate(taxonomy)}
    for e in events:
        idxs = sorted({idx_of[s] for s in (e.get("subjects") or []) if s in idx_of})
        if idxs:
            e["subject_indices"] = idxs


def _bucket_by_day(events: list[dict]) -> dict[str, list[dict]]:
    by_day: dict[str, list[dict]] = defaultdict(list)
    for event in events:
        by_day[f"{event['month']}-{event['day']}"].append(event)
    for key in by_day:
        by_day[key].sort(key=lambda e: -e.get("score", 0))
    return dict(by_day)


def _build_compact(by_day: dict[str, list[dict]]) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {}
    for day, events in by_day.items():
        compact_events = []
        for ev in events:
            ce: dict = {}
            for full_key, short_key in cache_format.COMPACT_FIELD_MAP.items():
                if full_key in ev:
                    ce[short_key] = ev[full_key]
            extra = ev.get("extra") or {}
            for full_key, short_key in cache_format.COMPACT_EXTRA_FIELDS.items():
                if full_key in extra and extra[full_key] not in (None, "", False):
                    ce[short_key] = extra[full_key]
            compact_events.append(ce)
        out[day] = compact_events
    return out


def _write_compact_js(js_out: Path, compact_by_day: dict, taxonomy_list: list) -> None:
    compact_taxonomy = [
        {"n": t.get("name", ""), "c": t.get("category", ""), "sc": t.get("subcategory", "")}
        for t in taxonomy_list
    ]
    with open(js_out, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build_fr_cache.py (combined). Do not edit.\n")
        f.write("const SUBJECT_TAXONOMY = ")
        f.write(html_embed.js_safe_dumps(compact_taxonomy))
        f.write(";\n")
        f.write("const EVENTS_CACHE = ")
        f.write(html_embed.js_safe_dumps(compact_by_day))
        f.write(";\n")


def build(json_out: Path, js_out: Path, html_out: Path | None) -> dict:
    scored: list[dict] = []
    invalid = 0
    per_source: dict[str, int] = {}

    for directory, modname in SOURCES:
        mod = _load_module(directory, modname)
        min_score = int(mod.threshold())
        count = 0
        for ev in mod.parse_corpus(directory):
            if event_contract.validate_event(ev):
                invalid += 1
                continue
            ev = dict(ev)
            ev["score"] = mod.score_event(ev)
            if ev["score"] >= min_score:
                scored.append(ev)
                count += 1
        per_source[mod.SOURCE] = count

    taxonomy_list = _synthesize_taxonomy(scored)
    _enrich(scored, taxonomy_list)
    by_day = _bucket_by_day(scored)

    json_out.write_text(json.dumps(by_day, ensure_ascii=False, indent=2), encoding="utf-8")
    compact = _build_compact(by_day)
    _write_compact_js(js_out, compact, taxonomy_list)

    html_synced = False
    if html_out and html_out.exists():
        html_synced = html_embed.sync_html_embed(js_out, html_out)

    return {
        "events_by_source": per_source,
        "total_events": len(scored),
        "invalid_dropped": invalid,
        "days_with_events": len(by_day),
        "taxonomy_subjects": len(taxonomy_list),
        "json_out": str(json_out),
        "js_out": str(js_out),
        "html_synced": html_synced,
    }


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="  %(message)s")
    ap = argparse.ArgumentParser(description="Build the combined Federal Register cache.")
    ap.add_argument("--json-out", type=Path, default=DEFAULT_JSON_OUT)
    ap.add_argument("--js-out", type=Path, default=DEFAULT_JS_OUT)
    ap.add_argument("--html", type=Path, default=DEFAULT_HTML)
    ap.add_argument("--no-html-sync", action="store_true")
    args = ap.parse_args()

    html = None if args.no_html_sync else args.html
    summary = build(args.json_out, args.js_out, html)
    for k, v in summary.items():
        print(f"  {k}: {v}")
    if html and not summary["html_synced"]:
        print("  NOTE: HTML not spliced (file missing or markers not found).")


if __name__ == "__main__":
    main()
