"""
Founders Online edition builder for the Records Stage shell.

Produces **`founders-online-stage.html`**: the *standard* Records Stage UI — the
same shell as `records-stage.html` / `federal-register-stage.html` — with the
Founders Online corpus spliced in.

That means it inherits, for free, the toolkit's graphic design and layout, the
multi-tweet preset campaign builder, the clearance editor, Word export, and the
shared image-search modal (NARA Catalog + Wikimedia Commons + Library of
Congress).

Mapping into the event contract (see `event_contract.py`):
  * source  = the edition ("Washington Papers", "Adams Papers", ...) so the
              shell's auto-discovered source-filter chips become per-founder
              filters.
  * year / month / day  from `date-from` (`YYYY-MM-DD`); month/day are
              zero-padded so the bucket key matches the shell's
              `String(month).padStart(2,"0")`-style lookup.
  * title   = document title;  url = permalink.
  No score (the shell only badges/min-score-filters FRUS), no subjects
  (Founders metadata carries none) — so the compact event is just {y,t,u,s}.

It does NOT edit the shared shell: unknown sources render with the neutral
fallback badge, and the AI drafter / image modal are already source-agnostic.

Source data: `founders-online-metadata.json` (~51 MB, gitignored). Download it
once in a browser — it sits behind an AWS WAF JS challenge — from
https://founders.archives.gov/Metadata/founders-online-metadata.json
See docs/founders-online-build.md.

Usage:
    python build_founders_stage.py
    python build_founders_stage.py --no-html-sync
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

import event_contract
import html_embed

HERE = Path(__file__).resolve().parent
META_FILE = HERE / "founders-online-metadata.json"
SHELL_HTML = HERE / "records-stage.html"            # the cleared, vendored shell
STAGE_TITLE = "Founders Online — Records Stage"      # <title> + <h1> for this instance
DEFAULT_JSON_OUT = HERE / "founders_events_cache.json"
DEFAULT_JS_OUT = HERE / "founders_events_cache.js"
DEFAULT_HTML = HERE / "founders-online-stage.html"


def parse_founders(meta_path: Path) -> tuple[list[dict], int]:
    """Read the bulk metadata and emit toolkit event dicts. Returns
    (events, skipped) where skipped counts blank/partial-date records."""
    data = json.loads(meta_path.read_text(encoding="utf-8"))
    events: list[dict] = []
    skipped = 0
    for r in data:
        df = (r.get("date-from") or "").strip()
        # Need a full YYYY-MM-DD: the On This Day browse and the year axis both
        # require it. 99.7% of records qualify; the rest (blank dates) are dropped.
        if len(df) != 10 or df[4] != "-" or df[7] != "-":
            skipped += 1
            continue
        y, m, d = df[:4], df[5:7], df[8:10]
        if not (m.isdigit() and d.isdigit() and 1 <= int(m) <= 12 and 1 <= int(d) <= 31):
            skipped += 1
            continue
        events.append({
            "source": (r.get("project") or "Founders Online").strip(),
            "year": int(y),
            "month": m,           # already zero-padded "01".."12"
            "day": d,             # already zero-padded "01".."31"
            "title": (r.get("title") or "").strip() or "(untitled)",
            "url": (r.get("permalink") or "").strip(),
        })
    return events, skipped


def _bucket_by_day(events: list[dict]) -> dict[str, list[dict]]:
    by_day: dict[str, list[dict]] = defaultdict(list)
    for ev in events:
        by_day[f"{ev['month']}-{ev['day']}"].append(ev)
    # The browser re-sorts each day by year; sort here too for a stable JSON.
    for key in by_day:
        by_day[key].sort(key=lambda e: e.get("year", 0))
    return dict(by_day)


def _build_compact(by_day: dict[str, list[dict]]) -> dict[str, list[dict]]:
    """Founders needs only {y,t,u,s} — no score, doc-type, classification, or
    subjects. Keeping it minimal also keeps the embedded cache small."""
    out: dict[str, list[dict]] = {}
    for day, events in by_day.items():
        out[day] = [
            {"y": ev["year"], "t": ev["title"], "u": ev["url"], "s": ev["source"]}
            for ev in events
        ]
    return out


def _write_compact_js(js_out: Path, compact_by_day: dict) -> None:
    with open(js_out, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build_founders_stage.py. Do not edit.\n")
        # Founders carries no subject taxonomy; an empty list keeps the shell's
        # topic filter inert (same as the Federal Register presidential side).
        f.write("const SUBJECT_TAXONOMY = [];\n")
        f.write("const EVENTS_CACHE = ")
        f.write(html_embed.js_safe_dumps(compact_by_day))
        f.write(";\n")


def build(json_out: Path, js_out: Path, html_out: Path | None) -> dict:
    if not META_FILE.exists():
        raise SystemExit(
            f"{META_FILE.name} not found. Download it in a browser (it is behind "
            "an AWS WAF challenge):\n"
            "  https://founders.archives.gov/Metadata/founders-online-metadata.json\n"
            f"and save it as {META_FILE}"
        )
    if not SHELL_HTML.exists():
        raise SystemExit(f"{SHELL_HTML.name} (the Records Stage shell) not found.")

    events, skipped = parse_founders(META_FILE)

    # Validate against the shared event contract (same gate as every edition).
    summary = event_contract.validate_events(events)
    if not summary["ok"]:
        for p in summary["problems"]:
            print(f"  INVALID: {p['event']}: {p['problems']}")
        raise SystemExit(f"{summary['invalid']} invalid events — aborting.")

    by_day = _bucket_by_day(events)
    json_out.write_text(json.dumps(by_day, ensure_ascii=False, indent=2), encoding="utf-8")
    compact = _build_compact(by_day)
    _write_compact_js(js_out, compact)

    per_source: dict[str, int] = defaultdict(int)
    for ev in events:
        per_source[ev["source"]] += 1

    html_synced = False
    if html_out:
        # Start every build from the cleared, vendored shell so the result is
        # always the canonical Records Stage UI plus fresh Founders data.
        shell = SHELL_HTML.read_text(encoding="utf-8")
        # Customize the title to match the sibling instances' house style
        # (e.g. "Federal Register — Records Stage"). The shell ships the generic
        # "Records Stage"; we rebuild from it each run, so re-apply every time.
        shell = shell.replace("<title>Records Stage</title>",
                              f"<title>{STAGE_TITLE}</title>")
        shell = shell.replace("<h1>Records Stage</h1>", f"<h1>{STAGE_TITLE}</h1>")
        html_out.write_text(shell, encoding="utf-8")
        html_synced = html_embed.sync_html_embed(js_out, html_out)

    return {
        "events": len(events),
        "skipped_blank_date": skipped,
        "days_with_events": len(by_day),
        "events_by_source": dict(sorted(per_source.items(), key=lambda kv: -kv[1])),
        "json_out": str(json_out),
        "js_out": str(js_out),
        "html": str(html_out) if html_out else None,
        "html_synced": html_synced,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description="Build founders-online-stage.html (Records Stage UI).")
    ap.add_argument("--json-out", type=Path, default=DEFAULT_JSON_OUT)
    ap.add_argument("--js-out", type=Path, default=DEFAULT_JS_OUT)
    ap.add_argument("--html", type=Path, default=DEFAULT_HTML)
    ap.add_argument("--no-html-sync", action="store_true")
    args = ap.parse_args()

    html = None if args.no_html_sync else args.html
    summary = build(args.json_out, args.js_out, html)
    for k, v in summary.items():
        print(f"  {k}: {v}")
    if html and not summary["html_synced"]:
        print("  NOTE: HTML not spliced (shell missing or markers not found).")
    elif html:
        mb = args.html.stat().st_size / 1024 / 1024
        print(f"  ✓ {args.html.name} written ({mb:.1f} MB)")


if __name__ == "__main__":
    main()
